name: Run Pytest

on:
  push:
    branches-ignore: [production]
  pull_request:
    branches: [production, develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.14
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run pytest
        run: poetry run pytest